# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    match(type: "appstore")
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_options: {
        provisioningProfiles: {
          "com.medina.app.stores" => "match AppStore com.medina.app.stores"
        }
      }
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true, # Optional: speeds up the process
      beta_app_review_info: {
        contact_email: "hsamfikky@icloud.com",
        contact_first_name: "Hussam",
        contact_last_name: "El-Fikky",
        contact_phone: "+201021895413",
        demo_account_name: "hosamafiky@gmail.com",
        demo_account_password: "123456789",
        notes: "This is a beta build for testing purposes."
      }
    )
  end
end
