# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

ENV["ANDROID_APP_ID"] = "1:978985818662:android:449f454e10a1d4401ae4e7"

platform :android do
  desc "Lane to build and distribute the android app"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --no-tree-shake-icons"
    firebase_app_distribution(
      app: ENV["ANDROID_APP_ID"],
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/apk/release/app-release.apk",
      testers: "hosamafiky@gmail.com, heshamheder674@gmail.com, eng.magwad@gmail.com",
      release_notes: "This is a beta release of the app",
    )
  end
end

