name: Android Fastlane Firebase App Distribution

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.3"
          channel: stable

      - name: Install Ruby
        uses: actions/setup-ruby@v1

      - name: Build and Distribute Android App
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
          ANDROID_APP_ID: ${{ secrets.ANDROID_APP_ID }}
        run: |
          flutter clean
          flutter pub get
          flutter build apk --release --no-tree-shake-icons
          fastlane android firebase_distribution
