name: FIREBASE_APP_DISTRIBUTION

on:
  push:
    branches:
      - main

jobs:
  distribute_to_firebase:
    runs-on: macos-latest
    steps:
      - name: SETUP NODE
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: CHECKOUT MY REPO CODE
        uses: actions/checkout@v3

      - name: SETUP JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17.0.9"
          distribution: "temurin"

      - name: SETUP FLUTTER
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: SETUP RUBY
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true
          working-directory: android

      - name: UPDATE PROJECT VERSION
        run: |
          flutter pub add pub_version_plus
          flutter pub global activate pub_version_plus
          dart run pub_version_plus:main patch
          dart run pub_version_plus:main build

      - name: BUILD AND DISTRIBUTE ANDROID APP
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
          ANDROID_APP_ID: ${{ secrets.ANDROID_APP_ID }}
        run: |
          bundle exec fastlane android firebase_android_production_app_distribution
        working-directory: android
