name: Android Fastlane Firebase App Distribution

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Build and test
        run: |
          ./gradlew assembleDebug
          ./gradlew test

      - name: Install Fastlane
        run: |
          gem install bundler
          bundle install
          bundle exec fastlane install_plugins

      - name: Build and distribute APK
        run: bundle exec fastlane android distribute

      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_CLI_TOKEN }}
          file: app/build/outputs/apk/debug/app-debug.apk
